### ISSUE TITLE
Error: getaddrinfo ENOTFOUND steemd.steemit.com

### ISSUE THREAD

**Issue by ghost** [p0o/steem-bot#4] opened 2018-01-14 11:12 UTC
Getting this error when I try to run:
````
Unhandled rejection Error: getaddrinfo ENOTFOUND steemd.steemit.com steemd.steemit.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
````
I believe it's related to [this issue with steem-js](https://github.com/steemit/steem-js/issues/312).

**Comment by TwinkieWInkie** [comment] 2018-01-26 00:25
Hmm.

Curious whether the listen event will be possible over http.
Otherwise we'd have to configure steemjs to run over a third party websocket.

I'll have a look at it tomorrow.

**Comment by qsCyberProject** [comment] 2018-02-18 13:03
I have the same issue. Does anyone have a workaround?

**Comment by worstcritic** [comment] 2018-03-01 01:38
steemd.steemit.com is no longer an active node.

I use api.steemit.com

Here is a list of active api nodes:
https://geo.steem.pl/

**Comment by qsCyberProject** [comment] 2018-03-05 18:18
How do I change the node that's being used?

**Comment by p0o** [comment] 2018-03-11 17:58
I will publish a fix for this by tomorrow

**Comment by p0o** [comment] 2018-03-12 11:05
Please install the new package <0.8.0> and let me know if the problem is fixed or not. You also can use the new two examples in the /example directory as well for error handling and changing the RPC node.

**Closed as completed** 2018-03-15 06:55 UTC
